<?php
/**
 * @file
 * Primary module file for the election_fptp module.
 */

/**
 * Form modifying function - voting form (election-post/%election_post/vote).
 */
function election_fptp_vote_form(&$form, &$form_state) {

  $post = $form_state['post'];
  $election = $post->election;

  // Load candidates.
  $candidates = election_candidate_load_by_post($post, array(ELECTION_CANDIDATE_HOPEFUL), TRUE, 'RAND()');
  $form_state['candidates'] = $candidates;

  if (!count($candidates)) {
    drupal_set_message(t('Voting is currently closed: there are no published candidates standing for this @post.', array('@post' => election_get_post_name($election->type))), 'warning', FALSE);
    $form['#disabled'] = TRUE;
    drupal_goto(election_post_uri_path($post));
  }

  $form['post'] = array(
    '#type' => 'item',
    '#title' => drupal_ucfirst(election_get_post_name($election->type)),
    '#markup' => t('@title (!view details)', array(
      '@title' => $post->title,
      '!view details' => l(t('view details'), election_post_uri_path($post)),
    )),
  );

  $form['help'] = array(
    '#prefix' => '<p>',
    '#markup' =>  t('Please select your preferred candidate.'),
    '#suffix' => '</p>',
  );

  if (count($candidates) > 1) {
    $form['help']['#markup'] .= ' ' . t('Candidates are displayed in a random order.');
  }

  foreach ($candidates as $candidate) {
    $candidate_options[$candidate->candidate_id] = theme('election_candidate_full_name', array('candidate' => $candidate));
  }

  $form['candidate_id'] = array(
    '#type' => 'select',
    '#options' => $candidate_options,
    '#required' => TRUE,
  );

  $form['#validate'][] = 'election_fptp_vote_form_validate';

}

/**
 * Validate the voting form.
 */
function election_fptp_vote_form_validate($form, &$form_state) {

  // Add 'candidate_id' to $form_state (so it's available for later).
  $form_state['candidate_id'] = $form_state['values']['candidate_id'];

}


/**
 * Implements hook_election_vote_ELECTION_TYPE_save().
 *
 * Save votes for an FPTP election.
 */
function election_fptp_election_vote_fptp_save($ballot_id, $post, $vote_form, $vote_form_state) {

  $vote_entry = array(
    'ballot_id' => $ballot_id,
    'election_id' => $post->election_id,
    'post_id' => $post->post_id,
    'candidate_id' => $vote_form_state['candidate_id'],
  );

  $success = db_insert('election_vote')
    ->fields($vote_entry)
    ->execute();

  return $success ? TRUE : FALSE;

}
